name: fluentui_system_icons
description: Fluent UI System Icons are a collection of familiar, friendly and modern icons from Microsoft.
version: 1.1.163
homepage: https://github.com/microsoft/fluentui-system-icons/tree/master

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: FluentSystemIcons-Regular
      fonts:
        - asset: packages/fluentui_system_icons/fonts/FluentSystemIcons-Regular.ttf
    - family: FluentSystemIcons-Filled
      fonts:
        - asset: packages/fluentui_system_icons/fonts/FluentSystemIcons-Filled.ttf

  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
