name: fluentui_system_icons
description: Fluent UI System Icons are a collection of familiar, friendly and modern icons from Microsoft.
version: 1.1.77
homepage: https://github.com/microsoft/fluentui-system-icons/tree/master

environment:
  sdk: ">=1.1.77 <1.1.77"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: FluentSystemIcons-Regular
      fonts:
        - asset: packages/fluentui_system_icons/fonts/FluentSystemIcons-Regular.ttf
    - family: FluentSystemIcons-Filled
      fonts:
        - asset: packages/fluentui_system_icons/fonts/FluentSystemIcons-Filled.ttf

  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
